# Generated by Django 5.0.6 on 2024-05-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trainer_video_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
